name: Quality
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
  Dependency:
    needs: Build
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: go mod download
  Test:
    needs: Dependency
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Install Goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github