name: Quality Gate
on: [push, pull_request]
jobs:
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'

      - name: Install Dependencies
        run: go mod download
  Quality:
    needs: Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'

      - name: Run Quality Code Analysis
        run: go vet ./...

      - name: Install Golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run Golint
        run: golint ./...
  Tests:
    needs: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'

      - name: Run Unit Tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Install Goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github