name: pagarme-go
on:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test

      - name: Quality Gate - Test coverage shall be above threshold
        env:
          TEST_COVERAGE_THRESHOLD: 0
        run: |
          echo "Quality Gate: Checking test coverage is above threshold"
          echo "Threshold: $TEST_COVERAGE_THRESHOLD %"
          
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          
          echo "Current test coverage: $totalCoverage %"
          
          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
            echo "OK"
          else
            echo "Current test coverage is bellow threshold. Please add more unit."
            echo "Failed"
            exit 1
          fi